INSERT INTO products (
        _product_category_id,
        _product_brand_id,
        name,
        description,
        display_image,
        markup_rate,
        net_price,
        minimum_quantity,
        quantity_in_hand,
        average_cost,
        average_cost_vat_rate,
        is_active,
        is_deleted
    )
VALUES (
        :_product_category_id,
        :_product_brand_id,
        :name,
        :description,
        :display_image,
        :markup_rate,
        :net_price,
        :minimum_quantity,
        :quantity_in_hand,
        :average_cost,
        :average_cost_vat_rate,
        :is_active,
        :is_deleted
    );